service: skill-rebuildfm-player

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  memorySize: 128
  timeout: 30
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
      Resource: "*"

package:
  include:
    - node_modules/

functions:
  main:
    handler: index.handler
    events:
      - alexaSkill:
          appId: ${env:SKILL_ID}
          enabled: true
  cacheUpdator:
    handler: cacheUpdator.handler
    events:
      - schedule: rate(10 minutes)
