service: skill-rebuildfm-player

plugins:
  - serverless-plugin-warmup
  - serverless-plugin-tracing

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs8.10
  memorySize: 640
  timeout: 30
  environment:
    S3_BUCKET_EPISODE: ${env:S3_BUCKET_EPISODE}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:GetItem"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
        - "s3:PutObjectAcl"
      Resource:
        - "arn:aws:s3:::${env:S3_BUCKET_EPISODE}/*"
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource:
        - Fn::Join:
          - ":"
          -
            - arn:aws:lambda
            - Ref: AWS::Region
            - Ref: AWS::AccountId
            - function:${self:service}-${opt:stage, self:provider.stage}-*
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"

resources:
  Resources:
    podcastEpisodeCache:
      Type: AWS::S3::Bucket
      DeletionPolicy: Retain
      Properties:
        LifecycleConfiguration:
          Rules:
            - Status: "Enabled"
              ExpirationInDays: 31
        BucketName: ${env:S3_BUCKET_EPISODE}

custom:
  warmup:
    memorySize: 128

package:
  include:
    - node_modules/

functions:
  main:
    handler: index.handler
    warmup: true
    tracing: true
    events:
      - alexaSkill:
          appId: ${env:SKILL_ID}
          enabled: true
  cacheUpdator:
    handler: cacheUpdator.handler
    events:
      - schedule: rate(5 minutes)
